// Generated by gencpp from file ur_control/RG2_GripRequest.msg
// DO NOT EDIT!


#ifndef UR_CONTROL_MESSAGE_RG2_GRIPREQUEST_H
#define UR_CONTROL_MESSAGE_RG2_GRIPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_control
{
template <class ContainerAllocator>
struct RG2_GripRequest_
{
  typedef RG2_GripRequest_<ContainerAllocator> Type;

  RG2_GripRequest_()
    {
    }
  RG2_GripRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ur_control::RG2_GripRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_control::RG2_GripRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RG2_GripRequest_

typedef ::ur_control::RG2_GripRequest_<std::allocator<void> > RG2_GripRequest;

typedef boost::shared_ptr< ::ur_control::RG2_GripRequest > RG2_GripRequestPtr;
typedef boost::shared_ptr< ::ur_control::RG2_GripRequest const> RG2_GripRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_control::RG2_GripRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_control::RG2_GripRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ur_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_control::RG2_GripRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_control::RG2_GripRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_control::RG2_GripRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ur_control::RG2_GripRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_control/RG2_GripRequest";
  }

  static const char* value(const ::ur_control::RG2_GripRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ur_control::RG2_GripRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RG2_GripRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_control::RG2_GripRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ur_control::RG2_GripRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UR_CONTROL_MESSAGE_RG2_GRIPREQUEST_H
